### ISSUE TITLE
Correct the Term Lexicon Range Computation

### ISSUE THREAD

**Issue by scampi** [rdelbru/SIREn#70]
There is a NPE when a range cannot be computed. This happens when the range threshold for, e.g., the MEDIUM group, is not met in `at org.sindice.siren.benchmark.generator.lexicon.TermLexiconWriter.writeTermFile(TermLexiconWriter.java:216)`. Since the threshold is not met, that specific group range data is not written to disk.

This NPE was thrown when using a SIndice dataset of size == 1.

```
Exception in thread "main" java.lang.NullPointerException
    at org.sindice.siren.benchmark.generator.lexicon.TermLexiconWriter.writeTermFile(TermLexiconWriter.java:247)
    at org.sindice.siren.benchmark.generator.lexicon.TermLexiconWriter.writeTermFiles(TermLexiconWriter.java:238)
    at org.sindice.siren.benchmark.generator.lexicon.TermLexiconWriter.create(TermLexiconWriter.java:105)
    at org.sindice.siren.benchmark.generator.lexicon.TermLexiconGenerator.createLexicon(TermLexiconGenerator.java:128)
    at org.sindice.siren.benchmark.generator.lexicon.TermLexiconGenerator.createLexicons(TermLexiconGenerator.java:120)
    at org.sindice.siren.benchmark.generator.lexicon.TermLexiconGenerator.generate(TermLexiconGenerator.java:75)
    at org.sindice.siren.benchmark.generator.lexicon.TermLexiconGeneratorCLI.parseAndExecute(TermLexiconGeneratorCLI.java:109)
    at org.sindice.siren.benchmark.generator.lexicon.TermLexiconGeneratorCLI.main(TermLexiconGeneratorCLI.java:115)
```

**Comment by rdelbru** [comment]
Deprecated
